---
- name: Add Epel repository
  package:
    name: epel-release
    state: present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Add httpd-tools
  package:
    name: httpd-tools
    state: present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install apache2-utils
  package:
    name: apache2-utils
    state: present
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Install python-pip
  package:
    name: python-pip
    state: present
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install python3-pip
  package:
    name: python3-pip
    state: present
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Copy requirements.txt
  copy:
    src: "files/requirements.txt"
    dest: "{{ stack_path }}/requirements.txt"

- name: Install dependencies
  pip:
    requirements: "{{ stack_path }}/requirements.txt"


