version: '3'
services:
  proxy:
    image: traefik:2.3
    command:
    - '--log.level=DEBUG'
    - '--api=true'
    - '--api.dashboard=true'
    - '--providers.docker.endpoint=unix:///var/run/docker.sock'
    - '--providers.docker.swarmMode=true'
    - '--providers.docker.exposedbydefault=false'
    - '--providers.docker.network=traefik-public'
    - '--entrypoints.web.address=:80'
{% if accesslog  %}
    - '--accesslog=true'
{% endif %}
{% if metrics  %}
    - '--metrics.prometheus=true'
    - '--entryPoints.metrics.address=:8082'
    - '--metrics.prometheus.entryPoint=metrics'
{% endif %}
{% if tracing and jaeger_agent_url != ""  %}
    - '--tracing.jaeger=true'
    - '--tracing.jaeger.samplingServerURL={{ jaeger_agent_url }}'
{% endif %}
{% if acme_email != "" %}
    - '--entrypoints.websecure.address=:443'
    - '--certificatesresolvers.letsencryptresolver.acme.httpchallenge=true'
    - '--certificatesresolvers.letsencryptresolver.acme.httpchallenge.entrypoint=web'
    - '--certificatesresolvers.letsencryptresolver.acme.email={{ acme_email }}' 
    - '--certificatesresolvers.letsencryptresolver.acme.storage=/letsencrypt/acme.json'
{% endif %}
    ports:
      - 80:80
      - 8082:8082
{% if acme_email != "" %}
      - 443:443
{% endif %}
    volumes:
{% if acme_email != "" %}
    - {{ stack_path }}/traefik/letsencrypt:/letsencrypt
{% endif %}

    - /var/run/docker.sock:/var/run/docker.sock:ro
    - {{ stack_path }}/traefik/usersfile:/usersfile
    networks:
    - traefik-public
    deploy:
      placement:
        constraints:
        - node.role == manager
      labels:
        - 'traefik.enable=true'

{% if acme_email != "" %}
      # HTTP Catchall for redirecting HTTP -> HTTPS
        - 'traefik.http.routers.http-catchall.rule=PathPrefix(`/`)'
        - 'traefik.http.routers.http-catchall.entrypoints=web'
        - 'traefik.http.routers.http-catchall.middlewares=redirect-to-https'
        - 'traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https'
        - 'traefik.http.routers.traefik.entrypoints=websecure'
        - 'traefik.http.routers.traefik.tls.certresolver=letsencryptresolver'
{% else %}
      - 'traefik.http.routers.traefik.entrypoints=web'
{% endif %}
      # Traefik dashboard
        - 'traefik.http.routers.traefik.rule=(Host(`{{ traefik_dashboad_name }}.{{ stack_domain }}`))' # Put in your stack_domain
        - 'traefik.http.routers.traefik.service=api@internal'
        - 'traefik.http.services.api@internal.loadbalancer.server.port=8081' 
        - 'traefik.http.routers.traefik.middlewares=traefik-auth'
        - 'traefik.http.middlewares.traefik-auth.basicauth.usersfile=/usersfile'



{% if acme_email != "" %}
volumes:
  acme-certs:
{% endif %}

networks:
  traefik-public:
    external: true